<hr/>
<p>Inspired by <a href="http://waxy.org/links/">waxy.org/links</a>.
Powered by <a href="https://github.com/Idnan/like-on-git">like-on-git</a> browser extension, <a href="http://pandoc.org/">Pandoc</a> document converter and <a href="https://www.gnu.org/software/make/">GNU Make</a>.</p>

<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-84156325-1', 'auto');
  ga('send', 'pageview');
</script>
